CREATE DATABASE PIZZARIA_PORRONTO;
USE PIZZARIA_PORRONTO;

CREATE TABLE USUARIOS (
    id_usuario INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL
);

CREATE TABLE PRATOS (
    id_prato INT PRIMARY KEY AUTO_INCREMENT,
    nome_prato VARCHAR(100) NOT NULL,
    usuario_id INT,
    FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id_usuario)
);
